'use strict';

const { expect } = require('chai');
const sinon = require('sinon');
const proxyquire = require('proxyquire');
const verificationHelper = require('../../ZelBack/src/services/verificationHelper');
const { loadSpecLibrary } = require('./fixtures/fluxSpec');

// The spec library is REAL here — see tests/unit/fixtures/fluxSpec.js for why.
// The sealing primitives (seal/unseal/generateSealKeypair/assertSealedEnvelope),
// buildIngressAttestMessage, IngressAttestation and verifySignature are pure
// crypto with no I/O, so this suite runs the actual scheme rather than a marker:
// what the service sealed is proved by UNSEALING it with the recipient private
// key, and what it signed is proved by VERIFYING it — which is also what makes
// the negative tests real (a tampered attestation fails because the signature
// genuinely does not cover it, not because a stub was told to say false).
//
// Stubbed: mongo (appsRepository), the broadcast, the event bus, and the two
// halves of this node's signing identity — its public key and the private key
// behind getFluxMessageSignature, which live in the benchmark channel. The
// signature the stub returns is nonetheless a REAL one over the REAL payload,
// produced with the node keypair below.
//
// ingressEncryptionKey is stubbed to a generated keypair rather than the baked-in
// fluxteam key, because the test needs the private half to read what was sealed.
// That is the module's own documented seam (config can point sealing at another
// keypair); the shape it returns is the real one.

// A real secp256k1 node identity, as used elsewhere in this suite.
const NODE_PRIVKEY = '5JTeg79dTLzzHXoJPALMWuoGDM8QmLj4n5f6MeFjx8dzsirvjAh';
const NODE_PUBKEY = '0474eb4690689bb408139249eda7f361b7881c4254ccbe303d3b4d58c2b48897d0f070b44944941998551f9ea0e1befd96f13adf171c07c885e62d0c2af56d3dab';
const TEST_KID = 'ft-test';

describe('ingressAttestationService tests', () => {
  let flux;
  let fluxteamKey;
  let service;
  let logStub;
  let fluxNetworkHelperStub;
  let fluxBroadcastHelperStub;
  let appsRepositoryStub;
  let senderStub;
  let fluxEventBusStub;
  let ingressKeyStub;

  before(async function loadLibrary() {
    this.timeout(30000);
    flux = await loadSpecLibrary();
    // Fluxteam's offline keypair, generated by the real primitive. The public
    // half is what nodes seal to; the private half never leaves this file.
    fluxteamKey = flux.generateSealKeypair();
  });

  function makeReq(overrides = {}) {
    return {
      socket: { remoteAddress: '203.0.113.7', remotePort: 51234 },
      headers: { 'user-agent': 'flux-cli/1.0' },
      ...overrides,
    };
  }

  /** The record the service handed the (stubbed) repository. */
  const storedRecord = () => appsRepositoryStub.storeIngressAttestation.firstCall.args[0];

  /** What was actually sealed, read back with fluxteam's private key. */
  function opened(record) {
    return JSON.parse(Buffer.from(flux.unseal(record.sealed, fluxteamKey.privateKey)).toString('utf8'));
  }

  /** A real sealed envelope for arbitrary contents. */
  function sealedFor(contents) {
    return flux.seal(JSON.stringify(contents), fluxteamKey.publicKey, { kid: TEST_KID });
  }

  /**
   * A genuine attestation from a peer: real envelope, real signature over the
   * real payload. `signOver` lets a test sign a DIFFERENT payload, which is what
   * a tampered record looks like on the wire.
   */
  function peerAttestation(overrides = {}) {
    const hash = overrides.hash ?? 'a'.repeat(64);
    const observedAt = overrides.observedAt ?? 1700000000000;
    const sealed = overrides.sealed ?? sealedFor({
      observed: { ip: '198.51.100.4', port: 40000 },
      asserted: { userAgent: null, forwardedFor: null },
    });
    const record = {
      hash, observedAt, node: NODE_PUBKEY, sealed,
    };
    const signature = verificationHelper.signMessage(
      flux.buildIngressAttestMessage(overrides.signOver ?? record), NODE_PRIVKEY,
    );
    return { ...record, signature };
  }

  beforeEach(() => {
    logStub = { error: sinon.stub(), warn: sinon.stub(), info: sinon.stub() };
    fluxNetworkHelperStub = { getFluxNodePublicKey: sinon.stub().resolves(NODE_PUBKEY) };
    fluxBroadcastHelperStub = {
      // The node's private key lives behind the benchmark channel, so the read is
      // stubbed — but it signs for real, so the attestation this node emits is
      // one any peer can verify.
      getFluxMessageSignature: sinon.stub().callsFake(
        async (message) => verificationHelper.signMessage(message, NODE_PRIVKEY),
      ),
    };
    appsRepositoryStub = {
      storeIngressAttestation: sinon.stub().resolves({ inserted: true }),
      getPermanentMessage: sinon.stub().resolves(null),
    };
    senderStub = { broadcastIngressAttestation: sinon.stub().resolves() };
    fluxEventBusStub = { publish: sinon.stub() };
    ingressKeyStub = {
      current: sinon.stub().returns({ kid: TEST_KID, publicKey: fluxteamKey.publicKey }),
    };

    service = proxyquire('../../ZelBack/src/services/appMessaging/ingressAttestationService', {
      '../../lib/log': logStub,
      '../fluxNetworkHelper': fluxNetworkHelperStub,
      '../utils/fluxBroadcastHelper': fluxBroadcastHelperStub,
      '../appDatabase/appsRepository': appsRepositoryStub,
      '../fluxCommunicationMessagesSender': senderStub,
      '../utils/fluxEventBus': fluxEventBusStub,
      '../utils/ingressEncryptionKey': ingressKeyStub,
    });
  });

  afterEach(() => {
    sinon.restore();
  });

  describe('emit', () => {
    it('captures the socket peer, seals it, stores locally, and broadcasts', async () => {
      await service.emit('a'.repeat(64), makeReq());

      expect(appsRepositoryStub.storeIngressAttestation.calledOnce).to.equal(true);
      const [record, expireAt] = appsRepositoryStub.storeIngressAttestation.firstCall.args;
      expect(record.hash).to.equal('a'.repeat(64));
      expect(record.node).to.equal(NODE_PUBKEY);
      expect(record.signature).to.be.a('string').and.have.length.greaterThan(0);
      // the source is carried only as the sealed envelope, never in cleartext
      expect(record.sealed.kid).to.equal(TEST_KID);
      expect(record.observed).to.equal(undefined);
      expect(record.asserted).to.equal(undefined);
      expect(JSON.stringify(record)).to.not.contain('203.0.113.7');
      // and what was sealed is the captured observed/asserted — proved by
      // opening it with fluxteam's private key, not by inspecting a marker
      expect(opened(record)).to.deep.equal({
        observed: { ip: '203.0.113.7', port: 51234 },
        asserted: { userAgent: 'flux-cli/1.0', forwardedFor: null },
      });
      expect(expireAt).to.be.a('number').and.greaterThan(Date.now());

      expect(senderStub.broadcastIngressAttestation.calledOnceWith(record)).to.equal(true);

      // Guard on the two stubbed collaborators that RECEIVE this record. The real
      // repository stores what a peer will later read back, and the real sender
      // puts it on the wire, where every receiving node rebuilds it through
      // IngressAttestation.deserialize and verifies it. So the record handed over
      // must survive exactly that — a field renamed or dropped here is a record
      // the network refuses, and neither stub would notice.
      const [broadcast] = senderStub.broadcastIngressAttestation.firstCall.args;
      expect(broadcast).to.equal(record);
      const rebuilt = flux.IngressAttestation.deserialize(record);
      expect(rebuilt.hash).to.equal(record.hash);
      expect(await rebuilt.verify(flux.verifySignature), 'a peer must be able to verify it').to.equal(true);
      expect(rebuilt.serialize()).to.deep.equal(record);
    });

    it('publishes a test-observability event carrying the sealing key id, not the source', async () => {
      await service.emit('a'.repeat(64), makeReq());
      expect(fluxEventBusStub.publish.calledOnce).to.equal(true);
      const [event, payload] = fluxEventBusStub.publish.firstCall.args;
      expect(event).to.equal('network:ingressattestation');
      expect(payload).to.deep.equal({ hash: 'a'.repeat(64), node: NODE_PUBKEY, kid: TEST_KID });
    });

    it('does not publish when the store was a duplicate', async () => {
      appsRepositoryStub.storeIngressAttestation.resolves({ inserted: false });
      await service.emit('a'.repeat(64), makeReq());
      expect(fluxEventBusStub.publish.called).to.equal(false);
    });

    it('normalizes an IPv4-mapped IPv6 address, leaving genuine IPv6 intact', async () => {
      await service.emit('a'.repeat(64), makeReq({ socket: { remoteAddress: '::ffff:198.51.100.9', remotePort: 40000 } }));
      expect(opened(storedRecord()).observed.ip).to.equal('198.51.100.9');

      appsRepositoryStub.storeIngressAttestation.resetHistory();
      await service.emit('b'.repeat(64), makeReq({ socket: { remoteAddress: '2001:db8::1', remotePort: 40000 } }));
      expect(opened(storedRecord()).observed.ip).to.equal('2001:db8::1');
    });

    it('captures and caps client-asserted headers before sealing', async () => {
      const longUa = 'u'.repeat(flux.USER_AGENT_MAX + 488);
      await service.emit('a'.repeat(64), makeReq({
        headers: { 'user-agent': longUa, 'x-forwarded-for': '203.0.113.7, 10.0.0.1' },
      }));
      const { asserted } = opened(storedRecord());
      // capped at the library's own limit, read off the library
      expect(asserted.userAgent).to.have.length(flux.USER_AGENT_MAX);
      expect(asserted.forwardedFor).to.equal('203.0.113.7, 10.0.0.1');
    });

    it('gives an unconfirmed message an orphan TTL', async () => {
      await service.emit('a'.repeat(64), makeReq());
      const [, expireAt] = appsRepositoryStub.storeIngressAttestation.firstCall.args;
      expect(expireAt).to.be.a('number').and.greaterThan(Date.now());
    });

    it('persists a confirmed message attestation with no TTL', async () => {
      appsRepositoryStub.getPermanentMessage.resolves({ hash: 'a'.repeat(64) });
      await service.emit('a'.repeat(64), makeReq());
      const [, expireAt] = appsRepositoryStub.storeIngressAttestation.firstCall.args;
      expect(expireAt).to.equal(null);
    });

    it('signs the sealed envelope — the raw source is never in the signed payload', async () => {
      await service.emit('a'.repeat(64), makeReq());
      const record = storedRecord();
      const signedMessage = fluxBroadcastHelperStub.getFluxMessageSignature.firstCall.args[0];
      // It is the library's own attestation payload over the SEALED envelope,
      // byte for byte — not merely a string that happens to mention the kid.
      expect(signedMessage).to.equal(flux.buildIngressAttestMessage({
        hash: record.hash,
        observedAt: record.observedAt,
        node: record.node,
        sealed: record.sealed,
      }));
      expect(signedMessage).to.contain(record.sealed.ct); // the ciphertext
      expect(signedMessage).to.not.contain('203.0.113.7'); // never the cleartext source
    });

    it('skips entirely when the source address cannot be determined', async () => {
      await service.emit('a'.repeat(64), makeReq({ socket: {} }));
      // nothing sealed, so nothing to sign, store or gossip
      expect(fluxBroadcastHelperStub.getFluxMessageSignature.called).to.equal(false);
      expect(appsRepositoryStub.storeIngressAttestation.called).to.equal(false);
      expect(senderStub.broadcastIngressAttestation.called).to.equal(false);
    });

    it('is best-effort — a signing failure never throws or stores', async () => {
      fluxBroadcastHelperStub.getFluxMessageSignature.rejects(new Error('no key'));
      await service.emit('a'.repeat(64), makeReq());
      expect(appsRepositoryStub.storeIngressAttestation.called).to.equal(false);
      expect(senderStub.broadcastIngressAttestation.called).to.equal(false);
      expect(logStub.error.calledOnce).to.equal(true);
    });

    it('does nothing without a hash or a request', async () => {
      await service.emit(null, makeReq());
      await service.emit('a'.repeat(64), null);
      expect(appsRepositoryStub.storeIngressAttestation.called).to.equal(false);
    });
  });

  describe('receive', () => {
    it('verifies, stores, and asks to rebroadcast on first store', async () => {
      const inbound = peerAttestation();

      const result = await service.receive(inbound);

      expect(appsRepositoryStub.storeIngressAttestation.calledOnce).to.equal(true);
      expect(result).to.deep.include({ rebroadcast: true });
      expect(result.record.hash).to.equal('a'.repeat(64));
      // stored as the class serializes it — the record a peer would receive back
      expect(storedRecord()).to.deep.equal(inbound);
      // a peer store also publishes the observability event
      expect(fluxEventBusStub.publish.calledOnceWith('network:ingressattestation')).to.equal(true);
    });

    it('does not rebroadcast a duplicate', async () => {
      appsRepositoryStub.storeIngressAttestation.resolves({ inserted: false });
      const result = await service.receive(peerAttestation());
      expect(result.rebroadcast).to.equal(false);
    });

    it('quarantines an attestation naming a message this node does not hold', async () => {
      await service.receive(peerAttestation());
      expect(appsRepositoryStub.getPermanentMessage.calledOnce).to.equal(true);
      const [, expireAt] = appsRepositoryStub.storeIngressAttestation.firstCall.args;
      expect(expireAt).to.be.a('number').and.greaterThan(Date.now());
    });

    it('persists an attestation naming a message this node holds', async () => {
      appsRepositoryStub.getPermanentMessage.resolves({ hash: 'a'.repeat(64) });
      await service.receive(peerAttestation());
      const [, expireAt] = appsRepositoryStub.storeIngressAttestation.firstCall.args;
      expect(expireAt).to.equal(null);
    });

    it('derives durability from local message state, never from the sender', async () => {
      // A sync backfill used to be filed confirmed on the serving peer's word. Both
      // sources now take the same path, so a peer cannot make a record permanent by
      // asserting it is.
      await service.receive(peerAttestation());
      expect(appsRepositoryStub.getPermanentMessage.calledOnce).to.equal(true);
    });

    it('rejects and does not store an attestation with a bad signature', async () => {
      // A genuine signature, but over a DIFFERENT hash — the record as it arrives
      // is not what the peer signed, which is what lifting an attestation onto
      // another message looks like.
      const lifted = peerAttestation({
        signOver: {
          hash: 'b'.repeat(64),
          observedAt: 1700000000000,
          node: NODE_PUBKEY,
          sealed: sealedFor({ observed: { ip: '198.51.100.4', port: 40000 } }),
        },
      });

      const result = await service.receive(lifted);

      expect(result).to.be.instanceOf(Error);
      expect(result.message).to.include('failed signature verification');
      expect(appsRepositoryStub.storeIngressAttestation.called).to.equal(false);
    });

    it('rejects and does not store a malformed attestation', async () => {
      const result = await service.receive({ not: 'valid' });
      expect(result).to.be.instanceOf(Error);
      expect(result.message).to.include('malformed ingress attestation');
      expect(appsRepositoryStub.storeIngressAttestation.called).to.equal(false);
    });
  });
});
