'use strict';

const { expect } = require('chai');

const meshRuntimeConfig = require('../../ZelBack/src/services/appMesh/meshRuntimeConfig');
const meshDerivation = require('../../ZelBack/src/services/appMesh/meshDerivation');

// The golden text pins the generated config's assembly — ordering, the sshd
// block, and above all the firewall, where a rule without local_cidr drops
// every container packet silently. Addresses are DERIVED from real outpoints
// (the derivation itself is pinned in meshDerivation.test.js), never
// hand-transcribed, so static_host_map's container entries stay honest.
const APP = {
  instance: 'ab12cd34ef56',
  appUuid: '5db6f53acbbd9b38e949307e96601e573bd6437ddec08707e76a33f771b358ea',
  outpoint: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08:0',
};
const COMPONENT_SLOTS = [0x0b62a5e7];
const OWN_BLOCK = meshDerivation.nodeBlock(APP.appUuid, APP.outpoint);

// The second peer publishes two authorities — a rotation overlap — and gets
// one firewall rule pair per authority.
const PEERS = [
  {
    outpoint: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855:1',
    endpoint: '198.51.100.9:16240',
    caShas: ['a'.repeat(64)],
  },
  {
    outpoint: `${'b'.repeat(64)}:0`,
    endpoint: '203.0.113.7:16230',
    caShas: ['b'.repeat(64), 'c'.repeat(64)],
  },
].map((p) => ({
  ...p,
  address: meshDerivation.nodeAddress(APP.appUuid, p.outpoint),
  block: meshDerivation.nodeBlock(APP.appUuid, p.outpoint),
}));
const CLIENT_PUBKEY = 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFixture0000000000000000000000000000000000000 flux-mesh-client';

const PEERS_BY_ADDR = [...PEERS].sort((a, b) => (a.address < b.address ? -1 : 1));

// static_host_map: each peer's block base keyed to its endpoint, sorted by
// address; unsafe_routes send each peer's block via that base.
const HOST_MAP_LINES = PEERS_BY_ADDR.map((p) => `  "${p.address}": ["${p.endpoint}"]`);
const UNSAFE_ROUTE_LINES = ['  unsafe_routes:'].concat(
  PEERS_BY_ADDR.flatMap((p) => [`    - route: "${p.block}"`, `      via: "${p.address}"`]),
);

// Firewall: peers sorted by address, one rule per (peer, authority), both
// directions, every rule scoped by local_cidr.
const firewallLines = (direction) => [`  ${direction}:`].concat(
  PEERS_BY_ADDR.flatMap((p) => p.caShas.flatMap((caSha) => [
    '    - port: any',
    '      proto: any',
    `      ca_sha: "${caSha}"`,
    `      cidr: "${p.block}"`,
    `      local_cidr: "${OWN_BLOCK}"`,
  ])),
);

const GOLDEN_NEBULA = `${[
  '# Generated by FluxOS for mesh app ab12cd34ef56. Rewritten on membership',
  '# change; do not edit.',
  'pki:',
  '  ca: /dat/var/lib/flux-mesh/ab12cd34ef56/trust-bundle.pem',
  '  cert: /dat/var/lib/flux-mesh/ab12cd34ef56/host.crt',
  '  key: /dat/var/lib/flux-mesh/ab12cd34ef56/host.key',
  '  disconnect_invalid: true',
  'static_host_map:',
  ...HOST_MAP_LINES,
  'lighthouse:',
  '  am_lighthouse: false',
  '  hosts: []',
  '  local_allow_list:',
  '    "10.0.0.0/8": false',
  '    "172.16.0.0/12": false',
  '    "192.168.0.0/16": false',
  '    "169.254.0.0/16": false',
  'listen:',
  '  host: "0.0.0.0"',
  '  port: 16230',
  'punchy:',
  '  punch: true',
  '  respond: true',
  'relay:',
  '  am_relay: false',
  '  use_relays: false',
  'sshd:',
  '  enabled: true',
  '  listen: "127.0.0.1:2222"',
  '  host_key: /dat/var/lib/flux-mesh/ab12cd34ef56/ssh_host_ed25519_key',
  '  authorized_users:',
  '    - user: fluxos',
  '      keys:',
  `        - "${CLIENT_PUBKEY}"`,
  'tun:',
  '  dev: mesh0',
  '  mtu: 1420',
  ...UNSAFE_ROUTE_LINES,
  'firewall:',
  ...firewallLines('outbound'),
  ...firewallLines('inbound'),
].join('\n')}\n`;

const GOLDEN_TAYGA = `# Generated by FluxOS for mesh app ab12cd34ef56. Rewritten on membership
# change (tayga has no reload; the unit is restarted); do not edit.
tun-device siit0
ipv4-addr 192.0.0.2
ipv6-addr fdb2:8fa9:3450:71e1:203f:b499::
map 10.127.1.11 fdb2:8fa9:3450:76a8:bd32:a312:b62:a5e7
map 10.127.1.12 fdb2:8fa9:3450:98e6:a9ff:3df9:b62:a5e7
`;

describe('meshRuntimeConfig', () => {
  describe('nebulaConfig', () => {
    it('matches the golden config, members sorted by address, one rule pair per authority', () => {
      const text = meshRuntimeConfig.nebulaConfig({
        ...APP, listenPort: 16230, members: PEERS, sshClientPublicKey: CLIENT_PUBKEY,
      });
      expect(text).to.equal(GOLDEN_NEBULA);
    });

    it('static_host_map keys each peer base, and unsafe_routes send its block via that base', () => {
      const text = meshRuntimeConfig.nebulaConfig({
        ...APP, listenPort: 16230, members: PEERS, sshClientPublicKey: CLIENT_PUBKEY,
      });
      for (const p of PEERS) {
        expect(text).to.include(`"${p.address}": ["${p.endpoint}"]`);
        // A peer's container addresses are NOT static hosts; they are routed.
        const container = meshDerivation.memberAddress(APP.appUuid, p.outpoint, COMPONENT_SLOTS[0]);
        expect(text).to.not.include(`"${container}":`);
        expect(text).to.include(`- route: "${p.block}"`);
        expect(text).to.include(`via: "${p.address}"`);
      }
    });

    it('every firewall rule in both directions carries local_cidr', () => {
      const text = meshRuntimeConfig.nebulaConfig({
        ...APP, listenPort: 16230, members: PEERS, sshClientPublicKey: CLIENT_PUBKEY,
      });
      const rules = text.split('\n').filter((l) => l.includes('ca_sha:')).length;
      const localCidrs = text.split('\n').filter((l) => l.includes('local_cidr:')).length;
      expect(rules).to.equal(6);
      expect(localCidrs).to.equal(rules);
    });

    it('emits empty lists for a member with no peers yet, sshd still on', () => {
      const text = meshRuntimeConfig.nebulaConfig({
        ...APP, listenPort: 16230, members: [], sshClientPublicKey: CLIENT_PUBKEY,
      });
      expect(text).to.include('unsafe_routes: []');
      expect(text).to.include('outbound: []');
      expect(text).to.include('inbound: []');
      expect(text).to.include('disconnect_invalid: true');
      expect(text).to.include('sshd:\n  enabled: true');
    });

    it('rejects malformed members, ports and client keys', () => {
      expect(() => meshRuntimeConfig.nebulaConfig({
        ...APP, listenPort: 0, members: [], sshClientPublicKey: CLIENT_PUBKEY,
      })).to.throw(TypeError);
      expect(() => meshRuntimeConfig.nebulaConfig({
        ...APP, listenPort: 16230, members: [{}], sshClientPublicKey: CLIENT_PUBKEY,
      })).to.throw(TypeError);
      const singular = { ...PEERS[1], caShas: undefined, caSha: 'aaaa' };
      expect(() => meshRuntimeConfig.nebulaConfig({
        ...APP, listenPort: 16230, members: [singular], sshClientPublicKey: CLIENT_PUBKEY,
      })).to.throw(TypeError);
      const emptyShas = { ...PEERS[1], caShas: [] };
      expect(() => meshRuntimeConfig.nebulaConfig({
        ...APP, listenPort: 16230, members: [emptyShas], sshClientPublicKey: CLIENT_PUBKEY,
      })).to.throw(TypeError);
      expect(() => meshRuntimeConfig.nebulaConfig({
        ...APP, listenPort: 16230, members: [], sshClientPublicKey: 'a\nb',
      })).to.throw(TypeError);
      expect(() => meshRuntimeConfig.nebulaConfig({
        ...APP, listenPort: 16230, members: [],
      })).to.throw(TypeError);
    });
  });

  describe('taygaConfig', () => {
    it('matches the golden config, map sorted by IPv4', () => {
      const text = meshRuntimeConfig.taygaConfig({
        ...APP,
        mapEntries: [
          { ipv4: '10.127.1.12', ipv6: 'fdb2:8fa9:3450:98e6:a9ff:3df9:b62:a5e7' },
          { ipv4: '10.127.1.11', ipv6: 'fdb2:8fa9:3450:76a8:bd32:a312:b62:a5e7' },
        ],
      });
      expect(text).to.equal(GOLDEN_TAYGA);
    });

    it('rejects malformed map entries', () => {
      expect(() => meshRuntimeConfig.taygaConfig({ ...APP, mapEntries: [{ ipv4: '10.0.0.1' }] })).to.throw(TypeError);
    });
  });

  describe('firewallRules', () => {
    it('matches the golden rules', () => {
      const rules = meshRuntimeConfig.firewallRules({
        externalInterface: 'eth0',
        meshPort: 16230,
        transitSubnet: '169.254.108.0/30',
        transitNamespaceIp: '169.254.108.2',
      });
      expect(rules).to.deep.equal({
        pre: [[
          '-i', 'eth0', '-p', 'udp', '--dport', '16230',
          '-j', 'DNAT', '--to-destination', '169.254.108.2:16230',
        ]],
        post: [['-s', '169.254.108.0/30', '-j', 'MASQUERADE']],
        fwd: [
          ['-d', '169.254.108.0/30', '-j', 'ACCEPT'],
          ['-s', '169.254.108.0/30', '-j', 'ACCEPT'],
        ],
      });
    });

    it('rejects missing scoping inputs', () => {
      expect(() => meshRuntimeConfig.firewallRules({
        externalInterface: '', meshPort: 16230, transitSubnet: '169.254.108.0/30', transitNamespaceIp: '169.254.108.2',
      })).to.throw(TypeError);
      expect(() => meshRuntimeConfig.firewallRules({
        externalInterface: 'eth0', meshPort: 16230, transitSubnet: 'nope', transitNamespaceIp: '169.254.108.2',
      })).to.throw(TypeError);
    });
  });
});
