const { expect } = require('chai');

const meshRuntimeConfig = require('../../ZelBack/src/services/appMesh/meshRuntimeConfig');

// The golden texts pin the generated artifacts byte-for-byte. The nebula
// firewall is where this design fails silently (a rule without local_cidr
// drops every container packet with nothing logged), so a change here must be
// a deliberate, reviewed act — not a formatting drift.
const APP = {
  instance: 'ab12cd34ef56',
  appUuid: '5db6f53acbbd9b38e949307e96601e573bd6437ddec08707e76a33f771b358ea',
  outpoint: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08:0',
};
const PEERS = [
  {
    address: 'fdb2:8fa9:3450:9d94:6853:4b74::',
    block: 'fdb2:8fa9:3450:9d94:6853:4b74::/96',
    endpoint: '198.51.100.9:16240',
    caSha: 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
  },
  {
    address: 'fdb2:8fa9:3450:98e6:a9ff:3df9::',
    block: 'fdb2:8fa9:3450:98e6:a9ff:3df9::/96',
    endpoint: '203.0.113.7:16230',
    caSha: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  },
];

const GOLDEN_NEBULA = `# Generated by FluxOS for mesh app ab12cd34ef56. Rewritten on membership
# change; do not edit.
pki:
  ca: /dat/var/lib/flux-mesh/ab12cd34ef56/trust-bundle.pem
  cert: /dat/var/lib/flux-mesh/ab12cd34ef56/host.crt
  key: /dat/var/lib/flux-mesh/ab12cd34ef56/host.key
  disconnect_invalid: true
static_host_map:
  "fdb2:8fa9:3450:98e6:a9ff:3df9::": ["203.0.113.7:16230"]
  "fdb2:8fa9:3450:9d94:6853:4b74::": ["198.51.100.9:16240"]
lighthouse:
  am_lighthouse: false
  hosts: []
  local_allow_list:
    "10.0.0.0/8": false
    "172.16.0.0/12": false
    "192.168.0.0/16": false
    "169.254.0.0/16": false
listen:
  host: "0.0.0.0"
  port: 16230
punchy:
  punch: true
  respond: true
relay:
  am_relay: false
  use_relays: false
tun:
  dev: mesh0
  mtu: 1420
  unsafe_routes:
    - route: "fdb2:8fa9:3450:98e6:a9ff:3df9::/96"
      via: "fdb2:8fa9:3450:98e6:a9ff:3df9::"
    - route: "fdb2:8fa9:3450:9d94:6853:4b74::/96"
      via: "fdb2:8fa9:3450:9d94:6853:4b74::"
firewall:
  outbound:
    - port: any
      proto: any
      ca_sha: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
      cidr: "fdb2:8fa9:3450:98e6:a9ff:3df9::/96"
      local_cidr: "fdb2:8fa9:3450:76a8:bd32:a312::/96"
    - port: any
      proto: any
      ca_sha: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
      cidr: "fdb2:8fa9:3450:9d94:6853:4b74::/96"
      local_cidr: "fdb2:8fa9:3450:76a8:bd32:a312::/96"
  inbound:
    - port: any
      proto: any
      ca_sha: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
      cidr: "fdb2:8fa9:3450:98e6:a9ff:3df9::/96"
      local_cidr: "fdb2:8fa9:3450:76a8:bd32:a312::/96"
    - port: any
      proto: any
      ca_sha: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
      cidr: "fdb2:8fa9:3450:9d94:6853:4b74::/96"
      local_cidr: "fdb2:8fa9:3450:76a8:bd32:a312::/96"
`;

const GOLDEN_TAYGA = `# Generated by FluxOS for mesh app ab12cd34ef56. Rewritten on membership
# change (tayga has no reload; the unit is restarted); do not edit.
tun-device siit0
ipv4-addr 192.0.0.2
ipv6-addr fdb2:8fa9:3450:71e1:203f:b499::
map 10.88.1.11 fdb2:8fa9:3450:76a8:bd32:a312:b62:a5e7
map 10.88.1.12 fdb2:8fa9:3450:98e6:a9ff:3df9:b62:a5e7
`;

describe('meshRuntimeConfig', () => {
  describe('nebulaConfig', () => {
    it('matches the golden config, members sorted by address', () => {
      const text = meshRuntimeConfig.nebulaConfig({
        ...APP, listenPort: 16230, members: PEERS,
      });
      expect(text).to.equal(GOLDEN_NEBULA);
    });

    it('every firewall rule in both directions carries local_cidr', () => {
      const text = meshRuntimeConfig.nebulaConfig({
        ...APP, listenPort: 16230, members: PEERS,
      });
      const rules = text.split('\n').filter((l) => l.includes('ca_sha:')).length;
      const localCidrs = text.split('\n').filter((l) => l.includes('local_cidr:')).length;
      expect(rules).to.equal(4);
      expect(localCidrs).to.equal(rules);
    });

    it('emits empty lists for a member with no peers yet', () => {
      const text = meshRuntimeConfig.nebulaConfig({
        ...APP, listenPort: 16230, members: [],
      });
      expect(text).to.include('unsafe_routes: []');
      expect(text).to.include('outbound: []');
      expect(text).to.include('inbound: []');
      expect(text).to.include('disconnect_invalid: true');
    });

    it('rejects malformed members and ports', () => {
      expect(() => meshRuntimeConfig.nebulaConfig({ ...APP, listenPort: 0, members: [] })).to.throw(TypeError);
      expect(() => meshRuntimeConfig.nebulaConfig({ ...APP, listenPort: 16230, members: [{}] })).to.throw(TypeError);
    });
  });

  describe('taygaConfig', () => {
    it('matches the golden config, map sorted by IPv4', () => {
      const text = meshRuntimeConfig.taygaConfig({
        ...APP,
        mapEntries: [
          { ipv4: '10.88.1.12', ipv6: 'fdb2:8fa9:3450:98e6:a9ff:3df9:b62:a5e7' },
          { ipv4: '10.88.1.11', ipv6: 'fdb2:8fa9:3450:76a8:bd32:a312:b62:a5e7' },
        ],
      });
      expect(text).to.equal(GOLDEN_TAYGA);
    });

    it('rejects malformed map entries', () => {
      expect(() => meshRuntimeConfig.taygaConfig({ ...APP, mapEntries: [{ ipv4: '10.0.0.1' }] })).to.throw(TypeError);
    });
  });

  describe('firewallRules', () => {
    it('matches the golden rules', () => {
      const rules = meshRuntimeConfig.firewallRules({
        externalInterface: 'eth0',
        meshPort: 16230,
        transitSubnet: '169.254.108.0/30',
        transitNamespaceIp: '169.254.108.2',
      });
      expect(rules).to.deep.equal({
        pre: [[
          '-i', 'eth0', '-p', 'udp', '--dport', '16230',
          '-j', 'DNAT', '--to-destination', '169.254.108.2:16230',
        ]],
        post: [['-s', '169.254.108.0/30', '-j', 'MASQUERADE']],
        fwd: [
          ['-d', '169.254.108.0/30', '-j', 'ACCEPT'],
          ['-s', '169.254.108.0/30', '-j', 'ACCEPT'],
        ],
      });
    });

    it('rejects missing scoping inputs', () => {
      expect(() => meshRuntimeConfig.firewallRules({
        externalInterface: '', meshPort: 16230, transitSubnet: '169.254.108.0/30', transitNamespaceIp: '169.254.108.2',
      })).to.throw(TypeError);
      expect(() => meshRuntimeConfig.firewallRules({
        externalInterface: 'eth0', meshPort: 16230, transitSubnet: 'nope', transitNamespaceIp: '169.254.108.2',
      })).to.throw(TypeError);
    });
  });
});
