'use strict';

process.env.NODE_CONFIG_DIR = `${process.cwd()}/tests/unit/globalconfig`;

const { expect } = require('chai');

const {
  FUTURE_BLOCKS_TOLERANCE,
  JUDGEMENT,
  REASON,
  DISCARDED,
  verdictPayload,
  alivePayload,
  collectorRanking,
  collectors,
  assemble,
  verifyCertificate,
} = require('../../ZelBack/src/services/utils/nodeDownCertificates');

// Same provenance as peerRings.test.js: generated by flux-peer-sim's
// tools/gen_peering_fixture.py (repo at 85e8657), verified by the Rust port.
// The payload vectors are byte-normative — the signatures are the sim's
// Ed25519 stand-in and are NOT verified here; FluxOS's secp256k1 seam is
// injected and exercised by the matrix below.
const fixture = require('./fixtures/rings-fixture.json');

describe('nodeDownCertificates canonical form (fixture: rings-fixture.json)', () => {
  it('encodes every signed verdict vector byte-for-byte', () => {
    let vectors = 0;
    const mismatches = [];
    fixture.fleets.forEach((fleet) => {
      fleet.signed_verdicts.forEach((vector) => {
        vectors += 1;
        const payload = verdictPayload({
          subject: vector.subject,
          juror: vector.juror,
          judgement: vector.judgement,
          height: vector.height,
          fingerprint: vector.fingerprint,
        });
        const got = payload === null ? null : payload.toString('hex');
        if (got !== vector.payload_hex) {
          mismatches.push({ juror: vector.juror, got, want: vector.payload_hex });
        }
      });
    });
    expect(vectors).to.equal(762);
    expect(mismatches).to.deep.equal([]);
  });

  it('encodes every alive vector byte-for-byte', () => {
    let vectors = 0;
    const mismatches = [];
    fixture.fleets.forEach((fleet) => {
      fleet.signed_alives.forEach((vector) => {
        vectors += 1;
        const payload = alivePayload(vector.subject, vector.height);
        const got = payload === null ? null : payload.toString('hex');
        if (got !== vector.payload_hex) {
          mismatches.push({ subject: vector.subject, got, want: vector.payload_hex });
        }
      });
    });
    expect(vectors).to.equal(145);
    expect(mismatches).to.deep.equal([]);
  });

  it('computes every collector ranking exactly, order included', () => {
    const mismatches = [];
    fixture.fleets.forEach((fleet) => {
      const byKey = new Map(fleet.nodes.map((node) => [node.key, node]));
      Object.entries(fleet.collector_ranking).forEach(([subjectKey, want]) => {
        const jury = fleet.juries[subjectKey].map((key) => byKey.get(key));
        const got = collectorRanking(subjectKey, jury).map((w) => w.key);
        if (JSON.stringify(got) !== JSON.stringify(want)) {
          mismatches.push({ subject: subjectKey, got, want });
        }
      });
    });
    expect(mismatches).to.deep.equal([]);
  });

  it('refuses to encode a field carrying the separator', () => {
    expect(verdictPayload({
      subject: 'a|b', juror: 'j', judgement: 'unreachable', height: 1, fingerprint: 'f',
    })).to.equal(null);
    expect(alivePayload('a|b', 1)).to.equal(null);
  });

  it('collectors: r <= 0 is push-to-all, positive r is the ranking head', () => {
    const fleet = fixture.fleets[0];
    const byKey = new Map(fleet.nodes.map((node) => [node.key, node]));
    const subjectKey = fleet.nodes[0].key;
    const jury = fleet.juries[subjectKey].map((key) => byKey.get(key));
    expect(collectors(subjectKey, jury, 0).map((w) => w.key))
      .to.deep.equal(jury.map((w) => w.key));
    expect(collectors(subjectKey, jury, 3).map((w) => w.key))
      .to.deep.equal(fleet.collector_ranking[subjectKey].slice(0, 3));
  });
});

describe('nodeDownCertificates verification — the rejection matrix', () => {
  // Six watchers, five owners: w6 shares w5's owner, so the duplicate-owner
  // rule is testable against crafted watcher lists without trusting the walk.
  const watchers = [
    { key: 'w1', owner: 'o1' },
    { key: 'w2', owner: 'o2' },
    { key: 'w3', owner: 'o3' },
    { key: 'w4', owner: 'o4' },
    { key: 'w5', owner: 'o5' },
    { key: 'w6', owner: 'o5' },
  ];
  const NEEDED = 4; // quorumThreshold(6)
  const SAME_JURY = new Set(['fpA', 'fpA2']);
  const NOW = 100;
  const MAX_AGE = 10;
  const acceptAll = () => true;

  const verdict = (juror, over = {}) => ({
    subject: 'sub:0',
    juror,
    judgement: JUDGEMENT.UNREACHABLE,
    height: NOW,
    fingerprint: 'fpA',
    signature: 'sig',
    ...over,
  });

  const verify = (verdicts, over = {}) => verifyCertificate(
    { subject: 'sub:0', verdicts },
    over.watchers !== undefined ? over.watchers : watchers,
    over.sameJury || SAME_JURY,
    over.verifySignature || acceptAll,
    over.nowHeight !== undefined ? over.nowHeight : NOW,
    over.maxAgeBlocks !== undefined ? over.maxAgeBlocks : MAX_AGE,
    over.cotenants || new Set(),
  );

  it('accepts H distinct owners and nothing is discarded', () => {
    const result = verify([verdict('w1'), verdict('w2'), verdict('w3'), verdict('w4')]);
    expect(result).to.deep.equal({
      accepted: true, reason: REASON.ACCEPTED, counted: 4, needed: NEEDED, discarded: {},
    });
  });

  it('an empty certificate is malformed', () => {
    expect(verify([]).reason).to.equal(REASON.MALFORMED);
  });

  it('an unrebuildable fingerprint rejects whole — never applied, never relayed', () => {
    const result = verify([verdict('w1')], { watchers: null });
    expect(result.accepted).to.equal(false);
    expect(result.reason).to.equal(REASON.UNKNOWN_FINGERPRINT);
  });

  it('discards: unencodable or unsigned verdicts are malformed', () => {
    const result = verify([
      verdict('w|1'),
      verdict('w2', { signature: '' }),
      ...[verdict('w1'), verdict('w3'), verdict('w4'), verdict('w5')],
    ]);
    expect(result.discarded[DISCARDED.MALFORMED]).to.equal(2);
    expect(result.accepted).to.equal(true);
  });

  it('discards: a verdict about a different subject', () => {
    const result = verify([verdict('w1', { subject: 'other:0' })]);
    expect(result.discarded[DISCARDED.WRONG_SUBJECT]).to.equal(1);
  });

  it('discards: reachable and abstain never contribute to a certificate', () => {
    const result = verify([
      verdict('w1', { judgement: JUDGEMENT.REACHABLE }),
      verdict('w2', { judgement: JUDGEMENT.ABSTAIN }),
    ]);
    expect(result.discarded[DISCARDED.NOT_UNREACHABLE]).to.equal(2);
  });

  it('ages verdicts in blocks, both directions, exact at the boundaries', () => {
    const boundaryOld = verify([verdict('w1', { height: NOW - MAX_AGE })]);
    expect(boundaryOld.counted).to.equal(1);
    const tooOld = verify([verdict('w1', { height: NOW - MAX_AGE - 1 })]);
    expect(tooOld.discarded[DISCARDED.STALE]).to.equal(1);
    const boundaryFuture = verify([verdict('w1', { height: NOW + FUTURE_BLOCKS_TOLERANCE })]);
    expect(boundaryFuture.counted).to.equal(1);
    const tooFuture = verify([verdict('w1', { height: NOW + FUTURE_BLOCKS_TOLERANCE + 1 })]);
    expect(tooFuture.discarded[DISCARDED.STALE]).to.equal(1);
  });

  it('discards: a foreign jury before the watcher lookup, so a splice is never called a forgery', () => {
    const result = verify([verdict('stranger', { fingerprint: 'fpB' })]);
    expect(result.discarded[DISCARDED.FOREIGN_JURY]).to.equal(1);
    expect(result.discarded[DISCARDED.NOT_A_WATCHER]).to.equal(undefined);
  });

  it('discards: a signer the fingerprint never assigned', () => {
    const result = verify([verdict('stranger')]);
    expect(result.discarded[DISCARDED.NOT_A_WATCHER]).to.equal(1);
  });

  it('discards: a watcher sharing the subject address on the counter\'s list', () => {
    const result = verify([verdict('w1')], { cotenants: new Set(['w1']) });
    expect(result.discarded[DISCARDED.CO_TENANT]).to.equal(1);
  });

  it('discards: the same juror twice, and a second juror of one owner', () => {
    const result = verify([
      verdict('w1'), verdict('w1'),
      verdict('w5'), verdict('w6'),
    ]);
    expect(result.discarded[DISCARDED.DUPLICATE_SIGNER]).to.equal(1);
    expect(result.discarded[DISCARDED.DUPLICATE_OWNER]).to.equal(1);
    expect(result.counted).to.equal(2);
  });

  it('discards: a signature the injected seam refuses', () => {
    const rejectO2 = (owner) => owner !== 'o2';
    const result = verify(
      [verdict('w1'), verdict('w2'), verdict('w3'), verdict('w4')],
      { verifySignature: rejectO2 },
    );
    expect(result.discarded[DISCARDED.BAD_SIGNATURE]).to.equal(1);
    expect(result).to.include({ accepted: false, reason: REASON.SUB_QUORUM, counted: 3 });
  });

  it('a second same-jury fingerprint counts — the jury is the unit of agreement', () => {
    const result = verify([
      verdict('w1'), verdict('w2', { fingerprint: 'fpA2' }),
      verdict('w3'), verdict('w4', { fingerprint: 'fpA2' }),
    ]);
    expect(result.accepted).to.equal(true);
    expect(result.counted).to.equal(4);
  });
});

describe('nodeDownCertificates assembly mirrors verification', () => {
  const jury = [
    { key: 'w1', owner: 'o1' },
    { key: 'w2', owner: 'o2' },
    { key: 'w3', owner: 'o3' },
  ];
  const SAME_JURY = new Set(['fpA']);
  const verdict = (juror, over = {}) => ({
    subject: 'sub:0',
    juror,
    judgement: JUDGEMENT.UNREACHABLE,
    height: 5,
    fingerprint: 'fpA',
    signature: 'sig',
    ...over,
  });

  it('returns null below quorum, a certificate at it', () => {
    expect(assemble('sub:0', 'w1', 6, 'fpA', [verdict('w1')], jury, SAME_JURY))
      .to.equal(null);
    const certificate = assemble(
      'sub:0', 'w1', 6, 'fpA', [verdict('w1'), verdict('w2')], jury, SAME_JURY,
    );
    expect(certificate).to.include({
      subject: 'sub:0', assembler: 'w1', height: 6, fingerprint: 'fpA',
    });
    expect(certificate.verdicts.length).to.equal(2);
  });

  it('skips what verification would discard: unsigned, foreign, co-tenant, non-juror, repeat owner', () => {
    const certificate = assemble('sub:0', 'w1', 6, 'fpA', [
      verdict('w1', { signature: '' }),
      verdict('w1', { fingerprint: 'fpB' }),
      verdict('w1', { judgement: JUDGEMENT.REACHABLE }),
      verdict('stranger'),
      verdict('w3'),
      verdict('w1'),
      verdict('w1', { height: 7 }),
      verdict('w2'),
    ], jury, SAME_JURY, new Set(['w2']));
    expect(certificate.verdicts.map((v) => [v.juror, v.height]))
      .to.deep.equal([['w3', 5], ['w1', 5]]);
  });

  it('what assembly builds, verification accepts', () => {
    const certificate = assemble(
      'sub:0', 'w2', 6, 'fpA', [verdict('w1'), verdict('w2'), verdict('w3')], jury, SAME_JURY,
    );
    const result = verifyCertificate(certificate, jury, SAME_JURY, () => true, 6, 10);
    expect(result.accepted).to.equal(true);
    expect(result.counted).to.equal(3);
    expect(result.discarded).to.deep.equal({});
  });
});

describe('nodeDownCertificates severe quarantine — the count over the standing rows', () => {
  const { quarantineFromExpiries } = require('../../ZelBack/src/services/utils/nodeDownCertificates');
  const now = 1_700_000_000_000;
  const hour = 60 * 60 * 1000;

  it('below the threshold nothing is held: the count is reported, there is no lift time', () => {
    expect(quarantineFromExpiries([now + hour, now + 2 * hour], now))
      .to.deep.equal({ quarantined: false, count: 2, liftsAt: null });
  });

  it('at the threshold the subject is held until its oldest standing row ages out', () => {
    expect(quarantineFromExpiries([now + 3 * hour, now + hour, now + 2 * hour], now))
      .to.deep.equal({ quarantined: true, count: 3, liftsAt: now + hour });
  });

  it('every further certification moves the lift to the row whose expiry brings the count under the threshold', () => {
    expect(quarantineFromExpiries([now + hour, now + 2 * hour, now + 3 * hour, now + 4 * hour], now))
      .to.deep.equal({ quarantined: true, count: 4, liftsAt: now + 2 * hour });
  });

  it('an expired row counts for nothing, exactly at its boundary', () => {
    expect(quarantineFromExpiries([now, now + hour, now + 2 * hour], now))
      .to.deep.equal({ quarantined: false, count: 2, liftsAt: null });
  });
});

describe('nodeDownCertificates — the drop the verdict answers, and the certificate\'s since (P1)', () => {
  const { assemble, verifyCertificate, verdictPayload } = require('../../ZelBack/src/services/utils/nodeDownCertificates');
  const base = {
    subject: 'sub:0', juror: 'w1', judgement: JUDGEMENT.UNREACHABLE, height: 100, fingerprint: 'fpA',
  };

  it('a verdict without a drop encodes as it always has; with one, droppedAt and reason are two trailing signed fields', () => {
    const plain = verdictPayload(base).toString();
    expect(plain).to.equal('fluxnodedown-verdict:sub:0|w1|unreachable|100|fpA');
    const withDrop = verdictPayload({ ...base, droppedAt: 1_700_000_000_000, reason: 'shutdown' }).toString();
    expect(withDrop).to.equal('fluxnodedown-verdict:sub:0|w1|unreachable|100|fpA|1700000000000|shutdown');
  });

  it('refuses to encode half a drop, a non-integer droppedAt, or an unknown reason', () => {
    expect(verdictPayload({ ...base, droppedAt: 1_700_000_000_000 })).to.equal(null);
    expect(verdictPayload({ ...base, reason: 'shutdown' })).to.equal(null);
    expect(verdictPayload({ ...base, droppedAt: 1.5, reason: 'shutdown' })).to.equal(null);
    expect(verdictPayload({ ...base, droppedAt: '1700000000000', reason: 'shutdown' })).to.equal(null);
    expect(verdictPayload({ ...base, droppedAt: 1_700_000_000_000, reason: 'rebooting' })).to.equal(null);
  });

  const watchers = [
    { key: 'w1', owner: 'o1' }, { key: 'w2', owner: 'o2' }, { key: 'w3', owner: 'o3' },
    { key: 'w4', owner: 'o4' }, { key: 'w5', owner: 'o5' }, { key: 'w6', owner: 'o6' },
  ];
  const sameJury = new Set(['fpA']);
  const v = (juror, over = {}) => ({ ...base, juror, signature: 'sig', ...over });
  const T = 1_700_000_000_000;

  it('assembly stamps since as the latest droppedAt among the counted verdicts, and reason as that verdict\'s', () => {
    const certificate = assemble('sub:0', 'w1', 100, 'fpA', [
      v('w1', { droppedAt: T - 5000, reason: 'unannounced' }),
      v('w2', { droppedAt: T, reason: 'shutdown' }),
      v('w3'), // a wake-up look: saw no drop
      v('w4', { droppedAt: T - 1000, reason: 'shutdown' }),
    ], watchers, sameJury);
    expect(certificate.since).to.equal(T);
    expect(certificate.reason).to.equal('shutdown');
  });

  it('a certificate whose verdicts saw no drop has no since and reason unannounced', () => {
    const certificate = assemble('sub:0', 'w1', 100, 'fpA', [v('w1'), v('w2'), v('w3'), v('w4')], watchers, sameJury);
    expect(certificate.since).to.equal(null);
    expect(certificate.reason).to.equal('unannounced');
  });

  it('verification re-derives since and reason and refuses a certificate that says otherwise', () => {
    const verdicts = [v('w1', { droppedAt: T, reason: 'restart' }), v('w2'), v('w3'), v('w4')];
    const ok = verifyCertificate({ subject: 'sub:0', verdicts, since: T, reason: 'restart' }, watchers, sameJury, () => true, 100, 10);
    expect(ok.accepted).to.equal(true);
    const moved = verifyCertificate({ subject: 'sub:0', verdicts, since: T + 60_000, reason: 'restart' }, watchers, sameJury, () => true, 100, 10);
    expect(moved).to.include({ accepted: false, reason: 'since_mismatch' });
    const relabelled = verifyCertificate({ subject: 'sub:0', verdicts, since: T, reason: 'shutdown' }, watchers, sameJury, () => true, 100, 10);
    expect(relabelled).to.include({ accepted: false, reason: 'since_mismatch' });
    const stripped = verifyCertificate({ subject: 'sub:0', verdicts }, watchers, sameJury, () => true, 100, 10);
    expect(stripped).to.include({ accepted: false, reason: 'since_mismatch' });
  });

  it('a certificate with no drop in it verifies with since absent, null, or reason unannounced alike', () => {
    const verdicts = [v('w1'), v('w2'), v('w3'), v('w4')];
    expect(verifyCertificate({ subject: 'sub:0', verdicts }, watchers, sameJury, () => true, 100, 10).accepted).to.equal(true);
    expect(verifyCertificate({ subject: 'sub:0', verdicts, since: null, reason: 'unannounced' }, watchers, sameJury, () => true, 100, 10).accepted).to.equal(true);
    expect(verifyCertificate({ subject: 'sub:0', verdicts, since: T, reason: 'unannounced' }, watchers, sameJury, () => true, 100, 10))
      .to.include({ accepted: false, reason: 'since_mismatch' });
  });

  it('what assembly builds with drops in it, verification accepts', () => {
    const verdicts = [v('w1', { droppedAt: T - 5000, reason: 'unannounced' }), v('w2', { droppedAt: T, reason: 'shutdown' }), v('w3'), v('w4')];
    const certificate = assemble('sub:0', 'w1', 100, 'fpA', verdicts, watchers, sameJury);
    expect(verifyCertificate(certificate, watchers, sameJury, () => true, 100, 10).accepted).to.equal(true);
  });
});
