'use strict';

process.env.NODE_CONFIG_DIR = `${process.cwd()}/tests/unit/globalconfig`;

const { expect } = require('chai');

const {
  M_OWNERS,
  quorumThreshold,
  inboundCap,
  PeerRings,
} = require('../../ZelBack/src/services/utils/peerRings');

// Cross-language conformance fixture, generated by flux-peer-sim's
// tools/gen_peering_fixture.py (repo at 85e8657) from the reference Python
// implementation and already verified by the Rust port. Regenerate there;
// never edit by hand. Jury membership is what a certificate is verified
// against, so every jury, duty set and successor list must match EXACTLY,
// order included — a near-miss evicts different nodes, not fails a test.
const fixture = require('./fixtures/rings-fixture.json');

describe('peerRings conformance (fixture: rings-fixture.json)', () => {
  it('carries the three fleets the reference emitted', () => {
    expect(fixture.fleets.map((f) => f.size)).to.deep.equal([20, 61, 300]);
    fixture.fleets.forEach((fleet) => {
      expect(fleet.nodes.length).to.equal(fleet.size);
    });
  });

  it('quorumThreshold matches the reference at every tabulated size', () => {
    const table = Object.entries(fixture.quorum_threshold);
    expect(table.length).to.be.greaterThan(0);
    table.forEach(([size, expected]) => {
      expect(quorumThreshold(Number(size)), `jury size ${size}`).to.equal(expected);
    });
  });

  it('inboundCap matches the reference at every tabulated fleet size', () => {
    const table = Object.entries(fixture.inbound_cap);
    expect(table.length).to.be.greaterThan(0);
    table.forEach(([size, expected]) => {
      expect(inboundCap(Number(size)), `fleet size ${size}`).to.equal(expected);
    });
  });

  fixture.fleets.forEach((fleet) => {
    describe(`fleet of ${fleet.size}`, () => {
      const rings = new PeerRings(fleet.nodes);

      it('computes every jury exactly, order included', () => {
        const mismatches = [];
        fleet.nodes.forEach((node) => {
          const got = rings.jury(node).map((juror) => juror.key);
          const want = fleet.juries[node.key];
          if (JSON.stringify(got) !== JSON.stringify(want)) {
            mismatches.push({ subject: node.key, got, want });
          }
        });
        expect(mismatches).to.deep.equal([]);
        expect(Object.keys(fleet.juries).length).to.equal(fleet.size);
      });

      it('juries never exceed M_OWNERS and never contain the subject or its owner', () => {
        fleet.nodes.forEach((node) => {
          const jury = rings.jury(node);
          expect(jury.length).to.be.at.most(M_OWNERS);
          jury.forEach((juror) => {
            expect(juror.key).to.not.equal(node.key);
            expect(juror.owner).to.not.equal(node.owner);
            expect(juror.addr).to.not.equal(node.addr);
          });
          const owners = jury.map((juror) => juror.owner);
          expect(new Set(owners).size).to.equal(owners.length);
        });
      });

      it('computes every duty set exactly', () => {
        const mismatches = [];
        fleet.nodes.forEach((node) => {
          const got = rings.duties(node).map((subject) => subject.key).sort();
          const want = fleet.duties[node.key];
          if (JSON.stringify(got) !== JSON.stringify(want)) {
            mismatches.push({ juror: node.key, got, want });
          }
        });
        expect(mismatches).to.deep.equal([]);
      });

      it('computes every successor walk exactly, order included', () => {
        const mismatches = [];
        fleet.nodes.forEach((node) => {
          const got = rings.ringSuccessors(node, 6, new Set()).map((s) => s.key);
          const want = fleet.ring_successors[node.key];
          if (JSON.stringify(got) !== JSON.stringify(want)) {
            mismatches.push({ me: node.key, got, want });
          }
        });
        expect(mismatches).to.deep.equal([]);
      });

      it('ringSuccessors records its picks in the exclude set', () => {
        const exclude = new Set();
        const picked = rings.ringSuccessors(fleet.nodes[0], 6, exclude);
        picked.forEach((node) => expect(exclude.has(node.key)).to.equal(true));
        const again = rings.ringSuccessors(fleet.nodes[0], 6, exclude);
        again.forEach((node) => {
          expect(picked.some((p) => p.key === node.key)).to.equal(false);
        });
      });

      it('isWitnessRelation holds exactly for jury and duty members', () => {
        const me = fleet.nodes[0];
        const related = new Set([
          ...fleet.juries[me.key],
          ...fleet.duties[me.key],
        ]);
        fleet.nodes.forEach((other) => {
          if (other.key === me.key) return;
          expect(rings.isWitnessRelation(me, other.key), other.key)
            .to.equal(related.has(other.key));
        });
      });
    });
  });
});
